import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import NextAuthSessionProvider from "./Provider";
import { ToastProvider } from "@/context/ToastContext";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider>
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
