# This workflow will build a Java project with Ant for a NetBeans project
# Optimized for the ITS-Projekt

name: Java CI with Ant

on:
  push:
    branches: [ "main", "AI" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install MySQL JDBC Driver
      run: |
        mkdir -p lib
        wget -O lib/mysql-connector-java-8.0.28.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.28/mysql-connector-java-8.0.28.jar
    
    - name: Create build directory
      run: mkdir -p build/classes
    
    - name: Compile Java files
      run: |
        javac -d build/classes -cp lib/mysql-connector-java-8.0.28.jar $(find src -name "*.java")
      continue-on-error: true
    
    - name: List compiled classes
      run: find build/classes -name "*.class" | sort
